version: '3.8'
services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - /srv/jekyll/vendor
    command: bundle exec jekyll serve --host 0.0.0.0 --watch --force_polling
